"""Local or private S3-compatible storage for attachments and model artifacts."""
import os
import tempfile
from pathlib import Path
from typing import BinaryIO, Protocol


class AttachmentStorage(Protocol):
    def save(self, key: str, fileobj: BinaryIO) -> None: ...
    def open(self, key: str) -> BinaryIO: ...
    def delete(self, key: str) -> None: ...


class LocalFilesystemStorage:
    """Stores each attachment as one file under ATTACHMENTS_DIR (default
    data/attachments), keyed by org_id/attachment_id/<sanitized filename> —
    never trusts the raw client filename as a path (no '..' traversal,
    no absolute paths)."""

    def __init__(self, base_dir: str | None = None):
        self.base_dir = Path(base_dir or os.environ.get("ATTACHMENTS_DIR")
                              or Path(__file__).parent.parent / "data" / "attachments")

    def _path(self, key: str) -> Path:
        # key is always generated by make_storage_key() below — this guard
        # exists so a future caller can't be tricked into escaping base_dir.
        full = (self.base_dir / key).resolve()
        if self.base_dir.resolve() not in full.parents and full != self.base_dir.resolve():
            raise ValueError("Invalid storage key")
        return full

    def save(self, key: str, fileobj: BinaryIO) -> None:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = None
        try:
            with tempfile.NamedTemporaryFile(dir=path.parent, delete=False) as out:
                temporary = out.name
                while chunk := fileobj.read(1024 * 1024):
                    out.write(chunk)
                out.flush()
                os.fsync(out.fileno())
            os.replace(temporary, path)
        finally:
            if temporary and os.path.exists(temporary):
                os.unlink(temporary)

    def open(self, key: str) -> BinaryIO:
        return open(self._path(key), "rb")

    def delete(self, key: str) -> None:
        path = self._path(key)
        if path.exists():
            path.unlink()


def sanitize_filename(filename: str) -> str:
    name = Path(filename or "upload").name  # strips any directory component
    return name[:200] or "upload"


def make_storage_key(org_id: str, attachment_id: str, filename: str) -> str:
    return f"{org_id}/{attachment_id}/{sanitize_filename(filename)}"


_default_storage: AttachmentStorage | None = None


class S3Storage:
    """Private S3-compatible storage shared by API and worker services.

    Credentials use the SDK credential chain. No public URLs or ACLs are
    created; downloads continue through the authenticated attachment API.
    """
    def __init__(self):
        import boto3
        self.bucket = os.environ["S3_BUCKET"]
        self.prefix = os.environ.get("S3_PREFIX", "terra-audit").strip("/")
        self.client = boto3.client("s3", endpoint_url=os.environ.get("S3_ENDPOINT_URL") or None,
                                   region_name=os.environ.get("AWS_DEFAULT_REGION") or None)

    def _key(self, key):
        if key.startswith("/") or "\\" in key or any(part in {"..", ".", ""} for part in key.split("/")):
            raise ValueError("Invalid storage key")
        return f"{self.prefix}/{key}" if self.prefix else key

    def save(self, key, fileobj):
        self.client.upload_fileobj(fileobj, self.bucket, self._key(key))

    def open(self, key):
        return self.client.get_object(Bucket=self.bucket, Key=self._key(key))["Body"]

    def delete(self, key):
        self.client.delete_object(Bucket=self.bucket, Key=self._key(key))


def get_storage() -> AttachmentStorage:
    global _default_storage
    if _default_storage is None:
        backend = os.environ.get("STORAGE_BACKEND", "local")
        if backend not in {"local", "s3"}:
            raise ValueError("STORAGE_BACKEND must be local or s3")
        _default_storage = S3Storage() if backend == "s3" else LocalFilesystemStorage()
    return _default_storage


def reset_storage() -> None:
    """Test-only: forces the next get_storage() call to re-read
    ATTACHMENTS_DIR — mirrors src.database's _ENGINE reset-per-test pattern
    (see tests/backend/conftest.py's isolated_db fixture)."""
    global _default_storage
    _default_storage = None
